### ISSUE TITLE
Feature request: Group nearest place markers

### ISSUE THREAD

**Issue by supaflybro** [jocafamaka/nagmapReborn#11]
On large installations a lot if place markers almost hanging a browser on a regular office PC, and looks like mess)
![image](https://user-images.githubusercontent.com/18231830/47648467-2c999580-db8b-11e8-83d7-6c4369414683.png)

**Comment by jocafamaka** [comment]
I understand the need of grouping when working with a large number of markers, but would lose the monitoring function if the information were to be hidden, because it is an environment with limited representations, would not be able to define the color of the marker that represents others which are grouped.

So I can not see uility in a real scenario.

Thank you for your time and contribution.

**Comment by supaflybro** [comment]
Yeah, you right. Also I think it will be hard to draw the connections between hosts and their parents.

**Comment by jocafamaka** [comment]
Hey.

Thinking about improving performance for large installations, was developed Lite version of the changesBar that you can see [here](https://github.com/jocafamaka/nagmapReborn/tree/developing#new-features).

This lite version is generated on the server side relieving the processing weight of the browser, it is added to the page in the form of an iframe that has auto refresh.

I'm also thinking of optionally removing some animations, but I'm still not sure.

Maybe it might be interesting for you.
