### ISSUE TITLE
how can i integration  nagmapReborn with centreon

### ISSUE THREAD

**Issue by chumwu** [jocafamaka/nagmapReborn#21]
I do config nagmapReborn and show it on web browser,but I can't integration  with centron,please help me?

**Comment by jocafamaka** [comment]
The integration with Centreon has been tested with version 2.8.x of it, so it is not possible to guarantee compatibility with versions prior to this.

So that I can provide you with better supportp please see [here](https://github.com/jocafamaka/nagmapReborn/wiki/How-to-request-support%3F) how to request support.
