### ISSUE TITLE
Addon nagmap is possible ?

### ISSUE THREAD

**Issue by SUPRVISOR** [jocafamaka/nagmapReborn#23]
Hello

I love your nagmap addon yet I try to improve with your agreement.

I would like to know if it would be possible to create a table with the status of equipment that is not referenced because there is no note latlng

This will allow me to just know the number of up / down in a group (ex cameras)

Catégories
Cameras: 4UP / 2DOWN
ADSL 1UP / 5DOWN
Is it possible ?

Thank you

Best Regards

Sorry my english is poor.

**Comment by jocafamaka** [comment]
First sorry for the delay.

Second, feel free to make any changes you want above the current code.

Third, it is possible to accomplish what you want, I recommend you take a look at [this function](https://github.com/jocafamaka/nagmapReborn/blob/master/marker.php#L25-L71)
Which is responsible for discarding hosts that have no LatLng definition ([here](https://github.com/jocafamaka/nagmapReborn/blob/master/marker.php#L44-L52)).

You can take advantage of this loop to store the information of the other hosts in a separate array for this reason.

And later in [this function](https://github.com/jocafamaka/nagmapReborn/blob/master/functions.php#L60-L136) that is responsible for defining the status of the hosts, you can also use this loop to capture only the information you need.

However, this will only be used for the initial data, it would be necessary to create a secondary script to perform the update of these data, as occurs with the [update.php](https://github.com/jocafamaka/nagmapReborn/blob/master/update.php) file;

Any questions I am at your disposal.

In addition to this I recommend you contact me through my email (joao_carlos.r@hotmail.com), so that you will possibly have quicker responses.
