### ISSUE TITLE
Broken communication with server

### ISSUE THREAD

**Issue by starejbar** [jocafamaka/nagmapReborn#29]
The issue will occure if you turn off filter bar in config.php
'filter' => 0 

Then the nagmap will stop updating host statuses showing following error:
`(NagmapReborn): This type of error is usually related to the following problem: The server is inaccessible or recusing connections, check the server and your connection. (TypeError: $(...).val() is undefined)`

**Comment by jocafamaka** [comment]
This is occurring due to an "if" that was lost during a conflict resolution in the search function; [In here](https://github.com/jocafamaka/nagmapReborn/commit/95948172d5b8cbe3a0b942d6cb8d7cb9124221f3).
This is now corrected; You can download the [v2.0.0 release](https://github.com/jocafamaka/nagmapReborn/releases/tag/v2.0.0) again;
