### ISSUE TITLE
Unable to initialize the class

### ISSUE THREAD

**Issue by wackou72** [jocafamaka/nagmapReborn#30]
Hello,
I tried to update from nagmap 1.6 to the 2.0 version.
I followed the installation process and migrate my config file using your parser, but first launching the website, I got the following error :

`Impossible d'initialiser la classe!

Détails: TypeError: Cannot read property 'forEach' of undefined

Stack: TypeError: Cannot read property 'forEach' of undefined at Host.createMarker (https://centreon.serac.fr/centreon/nagmap2/resources/js/classes/Host.js?v=2.0.0:45:19) at new Host (https://centreon.serac.fr/centreon/nagmap2/resources/js/classes/Host.js?v=2.0.0:13:22) at NagmapReborn.getHosts (https://centreon.serac.fr/centreon/nagmap2/resources/js/classes/NagmapReborn.js?v=2.0.0:216:28) at new NagmapReborn (https://centreon.serac.fr/centreon/nagmap2/resources/js/classes/NagmapReborn.js?v=2.0.0:37:31) at https://centreon.serac.fr/centreon/nagmap2/resources/js/app.js?v=2.0.0:211:35`

I have the necessary PHP extension : 

- php-common-5.4.16-48.el7.x86_64, include php-json
- php-mbstring

I changed all of my host to the new format.

When enabling the debug console, it create one host and then crash with the following error :
`10/08/2020 à 10:54:43 - TypeError: Cannot read property 'forEach' of undefined`

Let me know if you need more information.

**Comment by jocafamaka** [comment]
Hey,

In fact, this seems to be a problem that was never foreseen and really never happened before.

The problem is that one or more of your hosts does not have a hostgroup in their settings and this leads to an error in the [hostgroup listing function](https://github.com/jocafamaka/nagmapReborn/blob/v2.0.0/resources/js/classes/Host.js#L45), as it is not expected that there are no hostgroups.

To avoid this problem I made some changes to the code.

I ask you to download and test the code available on [that branch](https://github.com/jocafamaka/nagmapReborn/tree/no-hostgroup-fix).

I await your return.

Best regards.

**Comment by wackou72** [comment]
Hello,
I can confirm that it is working now !
Thanks 👍

**Comment by jocafamaka** [comment]
Great!!

Thank you for your feedback.
